import type { CrisisEvent } from "@/types/crisis";
import type { AtlasDecisionLogItem } from "@/modules/atlas/types";

/**
 * Datos demo profesionales usados solo cuando `/api/events` no devuelve
 * eventos suficientes (entorno local sin datos, demo comercial, etc.). No
 * contienen datos personales reales.
 */
export const atlasDemoEvents: CrisisEvent[] = [
  {
    id: "atlas-demo-wildfire",
    title: "Incendio forestal en zona periurbana",
    category: "fire",
    description: "Foco activo cerca de zona habitada, viento moderado hacia el sector residencial.",
    latitude: -33.42,
    longitude: -70.62,
    locationText: "Zona periurbana, sector poniente",
    severity: "CRITICAL",
    type: "ALERT",
    status: "UNDER_REVIEW",
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: "atlas-demo-landslide",
    title: "Corte de ruta por derrumbe",
    category: "infrastructure",
    description: "Ruta principal bloqueada tras derrumbe menor; tránsito desviado.",
    latitude: -33.05,
    longitude: -71.38,
    locationText: "Ruta costera, km 34",
    severity: "HIGH",
    type: "ALERT",
    status: "NEW",
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: "atlas-demo-weather",
    title: "Alerta meteorológica por vientos fuertes",
    category: "weather",
    description: "Ráfagas sostenidas sobre 70 km/h previstas para las próximas horas.",
    latitude: -36.82,
    longitude: -73.05,
    locationText: "Zona costera centro-sur",
    severity: "MEDIUM",
    type: "ALERT",
    status: "NEW",
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: "atlas-demo-earthquake",
    title: "Sismo moderado percibido",
    category: "earthquake",
    description: "Movimiento telúrico sin daños estructurales reportados hasta el momento.",
    latitude: -33.45,
    longitude: -70.65,
    locationText: "Región metropolitana",
    severity: "MEDIUM",
    type: "ALERT",
    status: "VALIDATED",
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: "atlas-demo-shelter",
    title: "Refugio con capacidad parcial disponible",
    category: "shelter",
    description: "Refugio municipal operando al 70% de capacidad, servicios básicos activos.",
    latitude: -33.44,
    longitude: -70.61,
    locationText: "Gimnasio municipal, sector oriente",
    severity: "LOW",
    type: "REPORT",
    status: "VALIDATED",
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: "atlas-demo-report-pending",
    title: "Reporte ciudadano de humo visible",
    category: "fire",
    description: "Vecino reporta columna de humo, aún sin confirmación oficial.",
    latitude: -33.41,
    longitude: -70.6,
    locationText: "Sector poniente, cerca del foco activo",
    severity: "HIGH",
    type: "REPORT",
    status: "NEW",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    isDemo: true,
  },
];

export const atlasDemoDecisionLog: AtlasDecisionLogItem[] = [
  {
    id: "log-1",
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    actor: "Analista ARGUS",
    action: "Alerta elevada a crítica por incendio forestal",
    module: "argus-atlas",
    severity: "critical",
  },
  {
    id: "log-2",
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    actor: "Operador institucional",
    action: "Reporte ciudadano validado (corte de ruta)",
    module: "argus-vigia",
    severity: "high",
  },
  {
    id: "log-3",
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    actor: "Sistema ARGUS",
    action: "Módulo AURA recomendado para incendio activo",
    module: "argus-aura",
    severity: "medium",
  },
];
