import type { ArcaAccessibility, ArcaShelter, ArcaShelterServices } from "@/modules/arca/types";

function services(overrides: Partial<ArcaShelterServices> = {}): ArcaShelterServices {
  return {
    water: "available",
    food: "available",
    electricity: "available",
    bathrooms: "available",
    showers: "unavailable",
    heating: "unavailable",
    internet: "unavailable",
    phoneCharging: "available",
    medicalPoint: "unavailable",
    psychologicalSupport: "unavailable",
    security: "available",
    childFriendlyArea: "unavailable",
    petFriendly: "unavailable",
    ...overrides,
  };
}

function accessibility(overrides: Partial<ArcaAccessibility> = {}): ArcaAccessibility {
  return {
    wheelchairAccessible: "unknown",
    reducedMobilitySupport: "unknown",
    elderlySupport: "unknown",
    childSupport: "unknown",
    petSupport: false,
    vehicleAccess: true,
    publicTransportAccess: true,
    ...overrides,
  };
}

/**
 * Refugios demo profesionales. Sin personas reales, sin direcciones
 * personales exactas. Marcados `isDemo: true`; no representan refugios
 * oficiales confirmados.
 */
export const arcaDemoShelters: ArcaShelter[] = [
  {
    id: "arca-demo-active",
    name: "Gimnasio municipal sector oriente",
    type: "sports_center",
    status: "active",
    capacityStatus: "available",
    location: { lat: -33.44, lng: -70.61, label: "Gimnasio municipal, sector oriente" },
    operator: { name: "Municipalidad (demo)", type: "municipal" },
    capacity: { total: 200, currentOccupancy: 60, available: 140, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
    services: services({ showers: "available" }),
    accessibility: accessibility({ wheelchairAccessible: true }),
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "high",
    publicNotes: "Refugio activo con capacidad disponible estimada.",
    createdAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-near-full",
    name: "Escuela República de Chile (demo)",
    type: "school",
    status: "limited",
    capacityStatus: "near_full",
    location: { lat: -33.42, lng: -70.58, label: "Sector residencial, calle secundaria" },
    operator: { name: "Establecimiento educacional (demo)", type: "government" },
    capacity: { total: 120, currentOccupancy: 104, available: 16, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString() },
    services: services({ medicalPoint: "limited" }),
    accessibility: accessibility(),
    needs: [
      {
        id: "need-1",
        type: "blankets",
        priority: "medium",
        quantityNeeded: 40,
        unit: "unidades",
        description: "Frazadas para familias recién llegadas.",
        status: "open",
        createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      },
    ],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "medium",
    publicNotes: "Refugio casi lleno. Verifique disponibilidad antes de desplazarse.",
    createdAt: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-closed",
    name: "Sede vecinal sector norte (demo)",
    type: "community_center",
    status: "closed",
    capacityStatus: "unknown",
    location: { lat: -33.36, lng: -70.67, label: "Sector norte" },
    capacity: { isEstimated: true },
    services: services({ water: "unavailable", food: "unavailable", electricity: "unavailable", bathrooms: "unavailable", security: "unavailable" }),
    accessibility: accessibility(),
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "medium",
    publicNotes: "Refugio cerrado temporalmente.",
    createdAt: new Date(Date.now() - 500 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-safe-zone",
    name: "Zona segura temporal plaza central",
    type: "safe_zone",
    status: "standby",
    capacityStatus: "unknown",
    location: { lat: -33.45, lng: -70.66, label: "Plaza central, zona abierta" },
    capacity: { isEstimated: true },
    services: services({ water: "limited", food: "unavailable", electricity: "unavailable", bathrooms: "limited" }),
    accessibility: accessibility({ wheelchairAccessible: true, vehicleAccess: false }),
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "low",
    publicNotes: "Zona de concentración temporal, no reemplaza refugio techado.",
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-sports-water-need",
    name: "Centro deportivo sector poniente",
    type: "sports_center",
    status: "active",
    capacityStatus: "available",
    location: { lat: -33.51, lng: -70.71, label: "Centro deportivo, sector poniente" },
    operator: { name: "Municipalidad (demo)", type: "municipal" },
    capacity: { total: 150, currentOccupancy: 40, available: 110, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString() },
    services: services({ water: "limited" }),
    accessibility: accessibility({ wheelchairAccessible: true }),
    needs: [
      {
        id: "need-2",
        type: "water",
        priority: "high",
        quantityNeeded: 500,
        unit: "litros",
        description: "Suministro de agua potable insuficiente para la ocupación actual.",
        status: "open",
        createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      },
    ],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "medium",
    publicNotes: "Refugio activo con necesidad de agua reportada.",
    createdAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-medical",
    name: "Refugio con punto médico sector centro",
    type: "medical_shelter",
    status: "active",
    capacityStatus: "available",
    location: { lat: -33.45, lng: -70.65, label: "Zona centro, vía pública" },
    operator: { name: "Cruz Roja local (demo)", type: "ngo" },
    capacity: { total: 80, currentOccupancy: 20, available: 60, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
    services: services({ medicalPoint: "available", psychologicalSupport: "available" }),
    accessibility: accessibility({ wheelchairAccessible: true, elderlySupport: true }),
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "high",
    publicNotes: "Cuenta con punto médico de atención primaria.",
    createdAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-pet-friendly",
    name: "Centro comunitario apto para mascotas",
    type: "community_center",
    status: "active",
    capacityStatus: "available",
    location: { lat: -33.47, lng: -70.64, label: "Sector oriente" },
    operator: { name: "Organización comunitaria (demo)", type: "community" },
    capacity: { total: 90, currentOccupancy: 25, available: 65, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString() },
    services: services({ petFriendly: "available" }),
    accessibility: accessibility({ petSupport: true }),
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "medium",
    publicNotes: "Acepta mascotas en área designada.",
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-no-accessibility",
    name: "Iglesia sector sur (demo)",
    type: "church",
    status: "active",
    capacityStatus: "available",
    location: { lat: -33.55, lng: -70.65, label: "Sector sur" },
    operator: { name: "Parroquia local (demo)", type: "community" },
    capacity: { total: 60, currentOccupancy: 10, available: 50, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 80 * 60 * 1000).toISOString() },
    services: services(),
    accessibility: accessibility({ wheelchairAccessible: false, reducedMobilitySupport: false }),
    restrictions: [{ id: "restr-1", type: "access_restricted", description: "Acceso por escalera, sin rampa habilitada." }],
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "low",
    publicNotes: "Sin accesibilidad confirmada para movilidad reducida.",
    createdAt: new Date(Date.now() - 220 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-hermes-pending",
    name: "Refugio periurbano con ruta pendiente",
    type: "evacuation_point",
    status: "standby",
    capacityStatus: "unknown",
    location: { lat: -33.38, lng: -70.72, label: "Ladera periurbana, sector poniente" },
    capacity: { isEstimated: true },
    services: services({ water: "unknown", electricity: "unavailable" }),
    accessibility: accessibility(),
    needs: [
      {
        id: "need-3",
        type: "transport",
        priority: "high",
        description: "Requiere confirmar ruta segura de acceso antes de habilitar traslados.",
        status: "open",
        createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      },
    ],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "low",
    publicNotes: "Punto de evacuación en espera; ruta con HERMES aún no confirmada.",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
  {
    id: "arca-demo-standby-municipal",
    name: "Edificio municipal sector centro",
    type: "municipal_building",
    status: "standby",
    capacityStatus: "available",
    location: { lat: -33.44, lng: -70.66, label: "Sector centro" },
    operator: { name: "Municipalidad (demo)", type: "municipal" },
    capacity: { total: 100, currentOccupancy: 0, available: 100, isEstimated: true, lastUpdatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
    services: services({ internet: "available" }),
    accessibility: accessibility({ wheelchairAccessible: true }),
    needs: [],
    linkedReports: [],
    linkedTalosAssessments: [],
    linkedHermesRoutes: [],
    linkedEvidence: [],
    confidence: "medium",
    publicNotes: "Refugio en espera, listo para activarse si es necesario.",
    createdAt: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isDemo: true,
    isPublic: true,
  },
];
