export type PagerAlertLevel = "green" | "yellow" | "orange" | "red" | "unknown";

export type EarthquakeShakingContext = {
  sourceId: "usgs-shakemap";
  sourceName: string;
  eventId: string;
  eventUrl?: string;
  shakemapId?: string;
  shakemapCode?: string;
  shakemapVersion?: string;
  shakemapStatus?: string;
  productSource?: string;
  generatedAt?: string;
  updatedAt?: string;
  magnitude?: number;
  depthKm?: number;
  epicenter: { lat?: number; lon?: number; place?: string };
  maxMmi?: number;
  mmiContours?: unknown;
  pga?: unknown;
  pgv?: unknown;
  psa03?: unknown;
  psa10?: unknown;
  psa30?: unknown;
  gridUrl?: string;
  shapeUrl?: string;
  rasterUrl?: string;
  kmlUrl?: string;
  stationListUrl?: string;
  faultGeometryUrl?: string;
  contourUrl?: string;
  uncertainty?: string;
  stations?: unknown;
  faultGeometry?: unknown;
  preferredProduct: boolean;
  confidence: number;
  limitations: string[];
  caveats: string[];
  evidenceRefs: string[];
};

export type EarthquakeImpactAssessmentContext = {
  sourceId: "usgs-pager";
  sourceName: string;
  eventId: string;
  eventUrl?: string;
  pagerProductId?: string;
  pagerCode?: string;
  pagerVersion?: string;
  pagerStatus?: string;
  productSource?: string;
  updatedAt?: string;
  alertLevelFatality: PagerAlertLevel;
  alertLevelEconomic: PagerAlertLevel;
  overallPagerAlert: PagerAlertLevel;
  populationExposureByMmi?: Record<string, number>;
  estimatedFatalitiesRange?: string;
  estimatedEconomicLossRange?: string;
  citiesExposed: string[];
  buildingVulnerabilityComments?: string;
  secondaryHazards: string[];
  historicAnalogues: string[];
  preferredProduct: boolean;
  confidence: number;
  limitations: string[];
  caveats: string[];
  evidenceRefs: string[];
};

export type EarthquakeOperationalImpactContext = {
  eventId: string;
  earthquakeIncidentId?: string;
  shakingContext?: EarthquakeShakingContext;
  impactAssessmentContext?: EarthquakeImpactAssessmentContext;
  maxMmi?: number;
  pagerAlert: PagerAlertLevel;
  populationExposureScore: number;
  impactScore: number;
  recommendedPriority: "P0" | "P1" | "P2" | "P3" | "P4";
  priorityReason: string;
  affectedInfrastructure: string[];
  affectedRoutes: string[];
  affectedMedicalFacilities: string[];
  tsunamiContext?: string;
  secondaryHazardContext: string[];
  uncertaintyScore: number;
  requiresReview: boolean;
  authorityCaveat: string;
  evidenceRefs: string[];
};
