import type { VigiaReport } from "@/modules/vigia/types";

/**
 * Reportes demo profesionales, usados solo cuando `/api/reports` no
 * devuelve suficientes reportes ciudadanos reales (entorno local sin datos,
 * demo comercial). Sin personas reales, sin direcciones reales.
 */
export const vigiaDemoReports: VigiaReport[] = [
  {
    id: "vigia-demo-smoke",
    type: "smoke",
    title: "Humo visible en zona norte",
    description: "Vecinos reportan columna de humo desde hace 20 minutos, sin llamas visibles aún.",
    severity: "high",
    status: "pending_validation",
    confidence: "medium",
    location: { lat: -33.36, lng: -70.67, label: "Sector norte, cerca de zona industrial" },
    reporter: { id: "demo-user-1", alias: "Vecino-2481", role: "CITIZEN", reputationScore: 62, isVerified: true },
    evidence: [
      {
        id: "ev-1",
        type: "photo",
        uploadedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        description: "Foto de la columna de humo a distancia",
        verificationStatus: "unverified",
      },
    ],
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-road-block",
    type: "road_block",
    title: "Corte de ruta por caída de árbol",
    description: "Árbol caído bloquea completamente un carril tras ráfagas de viento.",
    severity: "medium",
    status: "confirmed",
    confidence: "high",
    location: { lat: -33.47, lng: -70.64, label: "Avenida principal, sector oriente" },
    reporter: { id: "demo-user-2", alias: "Ciudadano-1190", role: "CITIZEN", reputationScore: 78, isVerified: true },
    evidence: [
      {
        id: "ev-2",
        type: "photo",
        uploadedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        verificationStatus: "verified",
      },
    ],
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-flood",
    type: "flood",
    title: "Anegamiento en paso bajo nivel",
    description: "Acumulación de agua tras lluvia intensa; vehículos livianos no pueden cruzar.",
    severity: "high",
    status: "under_review",
    confidence: "medium",
    location: { lat: -33.51, lng: -70.71, label: "Paso bajo nivel, sector poniente" },
    reporter: { id: "demo-user-3", alias: "Reportante-0552", role: "CITIZEN", reputationScore: 35, isVerified: false },
    evidence: [],
    createdAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-traffic",
    type: "traffic_accident",
    title: "Accidente vehicular con congestión",
    description: "Colisión entre dos vehículos genera congestión en ambos sentidos.",
    severity: "medium",
    status: "confirmed",
    confidence: "high",
    location: { lat: -33.44, lng: -70.61, label: "Cruce vial, sector centro" },
    reporter: { id: "demo-user-4", alias: "Vecino-3307", role: "CITIZEN", reputationScore: 55, isVerified: true },
    evidence: [
      { id: "ev-3", type: "photo", uploadedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(), verificationStatus: "pending" },
    ],
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-power",
    type: "power_outage",
    title: "Poste eléctrico dañado",
    description: "Poste inclinado tras impacto vehicular; cables sueltos cerca de la vereda.",
    severity: "high",
    status: "escalated",
    confidence: "high",
    location: { lat: -33.42, lng: -70.58, label: "Sector residencial, calle secundaria" },
    reporter: { id: "demo-user-5", alias: "Vecino-0871", role: "CITIZEN", reputationScore: 81, isVerified: true },
    evidence: [
      { id: "ev-4", type: "photo", uploadedAt: new Date(Date.now() - 100 * 60 * 1000).toISOString(), verificationStatus: "verified" },
    ],
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-medical",
    type: "medical_emergency",
    title: "Emergencia médica en vía pública",
    description: "Persona requiere atención médica urgente; equipo de emergencia ya fue notificado.",
    severity: "critical",
    status: "escalated",
    confidence: "medium",
    location: { lat: -33.45, lng: -70.66, label: "Zona centro, vía pública", isApproximate: true },
    reporter: { id: "demo-user-6", alias: "Ciudadano-7742", role: "CITIZEN", reputationScore: 60, isVerified: true },
    evidence: [],
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-wildfire",
    type: "fire",
    title: "Posible incendio forestal",
    description: "Foco de fuego visible en ladera cercana a zona periurbana, sin confirmación oficial aún.",
    severity: "critical",
    status: "pending_validation",
    confidence: "low",
    location: { lat: -33.38, lng: -70.72, label: "Ladera periurbana, sector poniente" },
    reporter: { id: "demo-user-7", alias: "Vecino-4420", role: "CITIZEN", reputationScore: 20, isVerified: false },
    evidence: [],
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
  {
    id: "vigia-demo-landslide",
    type: "landslide",
    title: "Derrumbe menor en talud",
    description: "Pequeño desprendimiento de tierra sobre la berma; no compromete la calzada aún.",
    severity: "low",
    status: "resolved",
    confidence: "verified",
    location: { lat: -33.06, lng: -71.4, label: "Ruta costera, km 36" },
    reporter: { id: "demo-user-8", alias: "Vecino-1005", role: "CITIZEN", reputationScore: 90, isVerified: true },
    evidence: [
      { id: "ev-5", type: "photo", uploadedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(), verificationStatus: "verified" },
    ],
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    source: "citizen",
    isDemo: true,
  },
];
