import { NextResponse } from "next/server";
import { demoKnowledgeIncidents, demoKnowledgeLessons } from "@/data/knowledgeIntakeDemo";
import { getEonetAdapterStatus } from "@/lib/knowledge-intake/adapters/eonetAdapter";
import { firmsAdapter } from "@/lib/knowledge-intake/adapters/firmsAdapter";
import { getGdacsAdapterStatus } from "@/lib/knowledge-intake/adapters/gdacsAdapter";
import { getNwsAdapterStatus } from "@/lib/knowledge-intake/adapters/nwsAdapter";
import { getNoaaNceiTsunamiAdapterStatus } from "@/lib/knowledge-intake/adapters/noaaNceiTsunamiAdapter";
import { getCoopsAdapterStatus } from "@/lib/knowledge-intake/adapters/noaaCoopsAdapter";
import { getIocSlsmfAdapterStatus } from "@/lib/knowledge-intake/adapters/iocSlsmfAdapter";
import { getNoaaStormEventsAdapterStatus } from "@/lib/knowledge-intake/adapters/noaaStormEventsAdapter";
import { getOpenFemaAdapterStatus } from "@/lib/knowledge-intake/adapters/openFemaAdapter";
import { getOpenMeteoAdapterStatus } from "@/lib/knowledge-intake/adapters/openMeteoAdapter";
import { getOpenAqAdapterStatus } from "@/lib/knowledge-intake/adapters/openAqAdapter";
import { getOsmOverpassAdapterStatus } from "@/lib/knowledge-intake/adapters/osmOverpassAdapter";
import { getUsgsWaterAdapterStatus } from "@/lib/knowledge-intake/adapters/usgsWaterAdapter";
import { getHapiAdapterStatus } from "@/lib/knowledge-intake/adapters/hdxHapiAdapter";
import { getWhoDonAdapterStatus } from "@/lib/knowledge-intake/adapters/whoDonAdapter";
import { getEcdcAdapterStatus } from "@/lib/knowledge-intake/adapters/ecdcAdapter";
import { getGdeltAdapterStatus } from "@/lib/knowledge-intake/adapters/gdeltAdapter";
import { getGlofasAdapterStatus } from "@/lib/knowledge-intake/adapters/copernicusGlofasAdapter";
import { getGfmAdapterStatus } from "@/lib/knowledge-intake/adapters/copernicusGfmAdapter";
import { reliefwebAdapter } from "@/lib/knowledge-intake/adapters/reliefwebAdapter";
import { usgsAdapter } from "@/lib/knowledge-intake/adapters/usgsAdapter";
import { getUsgsVolcanoHansAdapterStatus } from "@/lib/knowledge-intake/adapters/usgsVolcanoHansAdapter";
import { getGvpAdapterStatus } from "@/lib/knowledge-intake/adapters/smithsonianGvpAdapter";
import { getUsgsEarthquakeImpactAdapterStatus } from "@/lib/knowledge-intake/adapters/usgsEarthquakeImpactAdapter";
import { planKnowledgeIngestion } from "@/lib/knowledge-intake/ingestionPlanner";
import { getKnowledgeHealthFromDb } from "@/lib/knowledge-intake/persistence/knowledgePersistenceService";
import { getAllKnowledgeSources } from "@/lib/knowledge-intake/sourceRegistry";
import { getKnowledgeSourceStats } from "@/lib/knowledge-intake/sourceRegistry";
import type { ArgusKnowledgeInputType } from "@/types/knowledgeIntake";

export const dynamic = "force-dynamic";

export async function GET() {
  const stats = getKnowledgeSourceStats();
  const dbHealth = await getKnowledgeHealthFromDb().catch((error) => ({
    error: error instanceof Error ? error.message : "Knowledge DB health unavailable",
    persistedSources: 0,
    latestIngestionRuns: [],
    persistedIncidents: 0,
    persistedDocuments: 0,
    persistedLessons: 0,
    pendingReviews: 0,
    incidentsByDomain: [],
  }));
  const sources = getAllKnowledgeSources();
  const parserInputs: ArgusKnowledgeInputType[] = ["pdf", "txt_markdown", "csv", "json", "docx", "xlsx", "geojson", "rss_atom", "html"];
  const sourcesRequiringApiKey = sources.filter((source) => source.status === "requiresApiKey");
  const sourcesRequiringConfiguration = sources.filter((source) => source.status === "requiresConfiguration");
  const stubSources = sources.filter((source) => source.status === "stub" || source.status === "planned");
  const activeSourceDetails = sources.filter((source) => source.status === "active" || source.status === "active_contextual" || source.status === "active_historical" || source.status === "active_institutional");
  const nwsStatus = getNwsAdapterStatus();
  const noaaStormStatus = getNoaaStormEventsAdapterStatus();
  const noaaNceiTsunamiStatus = getNoaaNceiTsunamiAdapterStatus();
  const noaaCoopsStatus = getCoopsAdapterStatus();
  const iocSlsmfStatus = getIocSlsmfAdapterStatus();
  const openFemaStatus = getOpenFemaAdapterStatus();
  const openMeteoStatus = getOpenMeteoAdapterStatus();
  const openAqStatus = getOpenAqAdapterStatus();
  const osmStatus = getOsmOverpassAdapterStatus();
  const usgsWaterStatus = getUsgsWaterAdapterStatus();
  const hapiStatus = getHapiAdapterStatus();
  const whoDonStatus = getWhoDonAdapterStatus();
  const ecdcStatus = getEcdcAdapterStatus();
  const gdeltStatus = getGdeltAdapterStatus();
  const glofasStatus = getGlofasAdapterStatus();
  const gfmStatus = getGfmAdapterStatus();
  const gvpStatus = getGvpAdapterStatus();
  const earthquakeImpactStatus = getUsgsEarthquakeImpactAdapterStatus();
  const noKeySources = sources.filter((source) => source.id === "usgs_earthquake" || source.id === "usgs-shakemap" || source.id === "usgs-pager" || source.id === "usgs-earthquake-impact" || source.id === "gdacs" || source.id === "nasa-eonet" || source.id === "usgs-volcano-hans" || source.id === "smithsonian-gvp" || source.id === "nws" || source.id === "open-meteo" || source.id === "usgs-water" || source.id === "noaa-coops" || source.id === "noaa-storm-events" || source.id === "noaa-ncei-tsunami" || source.id === "openfema" || source.id === "osm-overpass" || source.id === "who-don" || source.id === "ecdc" || source.id === "gdelt");
  const optionalKeySources = sources.filter((source) => source.tags.some((tag) => tag.startsWith("optional_api_key:")));
  const fastActivationSources = sources.filter((source) => source.tags.includes("fast_activation") || source.tags.includes("no_api_key"));
  const contextualSources = sources.filter((source) => source.tags.includes("contextual_source") || source.sourceKinds.includes("contextual"));
  const historicalSources = sources.filter((source) => source.sourceKinds.includes("historical"));
  const datasetSources = sources.filter((source) => source.accessMethod === "dataset" || source.inputTypes.includes("downloaded_dataset"));
  const institutionalSources = sources.filter((source) => source.status === "active_institutional" || source.tags.includes("institutional_dataset"));
  return NextResponse.json({
    module: "ARGUS Knowledge Intake Engine",
    moduleVersion: "0.2-live-source-activation",
    buildVersion: "knowledge-intake-live-source-activation-phase",
    status: "controlled_live_ingestion",
    safetyMode: "informational_recommendations_only",
    totalSources: stats.total,
    activeSources: stats.active,
    activeSourceDetails: activeSourceDetails.map((source) => ({ id: source.id, name: source.name, status: source.status })),
    plannedSources: stats.planned,
    stubSources: stubSources.length,
    sourcesRequiringApiKey: sourcesRequiringApiKey.map((source) => ({
      id: source.id,
      name: source.name,
      requiredEnv: source.id === "nasa_firms" ? "NASA_FIRMS_MAP_KEY" : "unknown",
    })),
    sourcesRequiringConfiguration: sourcesRequiringConfiguration.map((source) => ({
      id: source.id,
      name: source.name,
      requiredEnv: source.id === "reliefweb" ? "RELIEFWEB_APP_NAME" : source.id === "ioc-slsmf" ? "IOC_SLSMF_API_KEY" : source.id === "openaq" ? "OPENAQ_API_KEY" : "unknown",
    })),
    noKeySources: noKeySources.map((source) => ({ id: source.id, name: source.name, status: source.status })),
    optionalKeySources: optionalKeySources.map((source) => ({
      id: source.id,
      name: source.name,
      optionalApiKey: source.tags.find((tag) => tag.startsWith("optional_api_key:"))?.replace("optional_api_key:", ""),
      apiKeyConfigured: source.id === "usgs-water" ? usgsWaterStatus.apiKeyConfigured : false,
      apiKeyRequired: false,
    })),
    historicalSources: historicalSources.map((source) => ({
      id: source.id,
      name: source.name,
      status: source.status,
      sourceRole: source.tags.find((tag) => tag.startsWith("sourceRole:"))?.replace("sourceRole:", "") ?? "historical_reference",
      isLiveSource: !source.tags.includes("isLiveSource:false"),
    })),
    datasetSources: datasetSources.map((source) => ({ id: source.id, name: source.name, status: source.status, accessMethod: source.accessMethod })),
    officialSources: sources.filter((source) => source.tags.includes("officialSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    hazardSources: sources.filter((source) => source.domains.some((domain) => ["tsunami", "earthquake", "volcano", "flood", "storm", "wildfire"].includes(domain))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    coastalRiskSources: sources.filter((source) => source.tags.some((tag) => tag.includes("coastal") || tag.includes("tsunami"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    coastalSources: sources.filter((source) => source.tags.some((tag) => tag.includes("coastal"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    oceanObservationSources: sources.filter((source) => source.tags.some((tag) => tag.includes("ocean_observation") || tag.includes("coastal_ocean"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    seaLevelSources: sources.filter((source) => source.domains.includes("sea_level_observation") || source.tags.includes("domain:sea_level_observation")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    tsunamiContextSources: sources.filter((source) => source.domains.includes("tsunami_sea_level_context") || source.tags.includes("domain:tsunami_sea_level_context")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    globalObservationSources: sources.filter((source) => source.tags.includes("official_global") || source.tags.includes("global_sea_level_context")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    tsunamiSources: sources.filter((source) => source.domains.includes("tsunami") || source.tags.includes("domain:tsunami")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    volcanoSources: sources.filter((source) => source.domains.includes("volcano") || source.tags.some((tag) => tag.includes("volcano"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    earthquakeSources: sources.filter((source) => source.domains.includes("earthquake") || source.tags.some((tag) => tag.includes("earthquake"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    impactSources: sources.filter((source) => source.tags.some((tag) => tag.includes("impact") || tag.includes("shakemap") || tag.includes("pager"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    scientificSources: sources.filter((source) => source.sourceKinds.includes("scientific") || source.tags.includes("scientificSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    globalKnowledgeSources: sources.filter((source) => source.tags.some((tag) => tag.includes("global") || tag.includes("knowledge"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    incidentCapableSources: sources.filter((source) => source.tags.some((tag) => tag.includes("isIncidentLayer:true") || tag.includes("incidentType:"))).map((source) => ({
      id: source.id,
      name: source.name,
      status: source.status,
      guardrails: source.id === "smithsonian-gvp" ? "reports_only_requiresReview" : source.tags.some((tag) => tag.includes("guardrail")) ? "guarded" : "source_specific",
    })),
    institutionalSources: institutionalSources.map((source) => ({
      id: source.id,
      name: source.name,
      status: source.status,
      sourceRole: source.tags.find((tag) => tag.startsWith("sourceRole:"))?.replace("sourceRole:", "") ?? "institutional_reference",
      isLiveSensor: false,
      institutionalLearning: source.tags.includes("institutionalLearning:enabled") ? "enabled" : "planned",
      playbookLearning: source.tags.includes("playbookLearning:enabled") ? "enabled" : "planned",
    })),
    fastActivationSources: fastActivationSources.map((source) => ({ id: source.id, name: source.name, status: source.status })),
    contextualSources: contextualSources.map((source) => ({
      id: source.id,
      name: source.name,
      status: source.status,
      role: source.tags.find((tag) => tag.startsWith("sourceRole:"))?.replace("sourceRole:", "") ?? "context",
      requiresApiKey: source.id === "openaq" || source.id === "ioc-slsmf",
      requiresConfiguration: source.status === "requiresConfiguration",
      optionalApiKey: source.tags.find((tag) => tag.startsWith("optional_api_key:"))?.replace("optional_api_key:", ""),
    })),
    humanitarianSources: sources.filter((source) => source.tags.includes("humanitarianSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status, sourceRole: source.tags.find((tag) => tag.startsWith("sourceRole:"))?.replace("sourceRole:", "") })),
    publicHealthSources: sources.filter((source) => source.tags.includes("publicHealthSource:true") || source.domains.includes("public_health")).map((source) => ({ id: source.id, name: source.name, status: source.status, requiresApiKey: source.tags.includes("apiKeyRequired:true") })),
    regionalHealthSources: sources.filter((source) => source.tags.includes("regionalSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    osintSources: sources.filter((source) => source.tags.includes("osintSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    mediaSignalSources: sources.filter((source) => source.tags.includes("mediaSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status, isIncidentSource: false })),
    earlyWarningSources: sources.filter((source) => source.tags.includes("earlyWarningSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    floodSources: sources.filter((source) => source.domains.includes("flood") || source.domains.includes("flood_context")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    forecastSources: sources.filter((source) => source.tags.includes("forecastSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    satelliteObservationSources: sources.filter((source) => source.tags.includes("satelliteObservationSource:true")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    airQualitySources: sources.filter((source) => source.domains.includes("air_quality") || source.tags.includes("domain:air_quality")).map((source) => ({ id: source.id, name: source.name, status: source.status, requiresApiKey: source.tags.includes("apiKeyRequired:true") })),
    smokeContextSources: sources.filter((source) => source.domains.includes("smoke_context") || source.tags.includes("domain:smoke_context")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    healthContextSources: sources.filter((source) => source.domains.includes("aura_respiratory_context") || source.domains.includes("aura_context") || source.domains.includes("public_health")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    geospatialSources: sources.filter((source) => source.tags.includes("sourceRole:critical_infrastructure_geospatial_source") || source.tags.some((tag) => tag.includes("geospatial"))).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    infrastructureSources: sources.filter((source) => source.domains.includes("critical_infrastructure") || source.tags.includes("critical_infrastructure_context")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    emergencyServiceSources: sources.filter((source) => source.domains.includes("emergency_services") || source.tags.includes("domain:emergency_services")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    environmentalSources: sources.filter((source) => source.domains.includes("environmental_hazard") || source.domains.includes("air_quality") || source.domains.includes("water_conditions")).map((source) => ({ id: source.id, name: source.name, status: source.status })),
    sourceCapabilities: [
      {
        sourceId: "smithsonian-gvp",
        status: "active_contextual_knowledge",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        optionalEnvVar: "GVP_WFS_BASE",
        officialSource: true,
        scientificSource: true,
        sourceRole: gvpStatus.sourceRole,
        isKnowledgeSource: true,
        isIncidentSource: "false for catalog/history; true with guardrails for DVAR/WVAR reports",
        phase1Capabilities: gvpStatus.phase1Capabilities,
        phase1_5_or_phase2Capabilities: gvpStatus.phase1_5_or_phase2Capabilities,
        mapLayers: gvpStatus.mapLayers,
        capabilities: gvpStatus.capabilities,
        limitations: gvpStatus.limitations,
        attribution: gvpStatus.attribution,
        citation: gvpStatus.citation,
      },
      {
        sourceId: "usgs-shakemap",
        status: "active_enrichment",
        ready: true,
        requiresApiKey: false,
        officialSource: true,
        sourceRole: "earthquake_ground_shaking_intensity_source",
        isIncidentSource: false,
        isEnrichmentSource: true,
        phase1Capabilities: ["MMI intensity", "PGA/PGV/PSA metadata/URLs", "ShakeMap contours/grid/shape URLs", "fault/station URLs when available", "shaking footprint context"],
        mapLayer: "USGS ShakeMap Intensity",
        limitations: ["Not prediction.", "Not damage confirmation.", "Early versions can change.", "Contours may be generalized.", "No evacuation or route closure."],
      },
      {
        sourceId: "usgs-pager",
        status: "active_enrichment",
        ready: true,
        requiresApiKey: false,
        officialSource: true,
        sourceRole: "earthquake_impact_assessment_source",
        isIncidentSource: false,
        isEnrichmentSource: true,
        phase1Capabilities: ["population exposure by MMI", "fatality alert estimate", "economic loss alert estimate", "affected cities when structured data is available", "vulnerability/secondary hazard notes"],
        mapLayer: "USGS PAGER Impact Assessment",
        limitations: ["Estimates, not confirmed losses.", "Can update.", "No evacuation, route closure, damage confirmation or casualty confirmation."],
      },
      {
        sourceId: "osm-overpass",
        status: "active_contextual",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        officialSource: false,
        aggregatorSource: false,
        communitySource: true,
        sourceRole: "critical_infrastructure_geospatial_source",
        isIncidentSource: false,
        coverage: "Global collaborative geospatial data, quality variable by region",
        runAllDefault: false,
        licenseStatus: "ODbL",
        attributionRequired: true,
        attribution: osmStatus.attribution,
        accessType: "overpass_ql_api",
        phase1Capabilities: osmStatus.phase1Capabilities,
        phase2Planned: osmStatus.phase2Planned,
        capabilities: osmStatus.capabilities,
        mapLayer: osmStatus.mapLayer,
        categories: osmStatus.categories,
        limitations: osmStatus.limitations,
        caveat: "Critical infrastructure context only; not an official universal registry, routing engine, geocoder, tile server or availability source.",
      },
      {
        sourceId: "hdx-hapi",
        status: hapiStatus.status,
        ready: hapiStatus.ready,
        requiresApiKey: true,
        requiresConfiguration: hapiStatus.requiresConfiguration,
        requiredEnv: "HAPI_APP_IDENTIFIER",
        optionalPhase2EnvVar: "HDX_API_TOKEN",
        officialSource: true,
        aggregatorSource: true,
        humanitarianSource: true,
        sourceRole: hapiStatus.sourceRole,
        isIncidentSource: false,
        runAllDefault: false,
        phase1Capabilities: hapiStatus.phase1Capabilities,
        phase2Planned: ["HDX CKAN metadata expansion", "HDX Tabular Data Endpoints", "selected dataset ingestion", "admin boundary geometry integration"],
        mapLayer: hapiStatus.mapLayer,
        limitations: hapiStatus.limitations,
        caveat: "Humanitarian context indicators only; not a live alert, operational order, clinical source, capacity confirmation or incident generator.",
      },
      {
        sourceId: "who-don",
        status: whoDonStatus.status,
        ready: true,
        requiresApiKey: false,
        sourceRole: whoDonStatus.sourceRole,
        isIncidentSource: true,
        officialSource: true,
        phase1Capabilities: whoDonStatus.phase1Capabilities,
        phase2Planned: ["ECDC", "PAHO", "CDC", "Africa CDC", "ReliefWeb health updates", "ministries of health"],
        mapLayer: whoDonStatus.mapLayer,
        limitations: whoDonStatus.limitations,
      },
      {
        sourceId: "ecdc",
        status: "active_contextual_incident_capable",
        ready: true,
        requiresApiKey: false,
        sourceRole: ecdcStatus.sourceRole,
        isIncidentSource: true,
        isContextSource: true,
        officialSource: true,
        phase1Capabilities: ecdcStatus.phase1Capabilities,
        phase2Planned: ["CDTR PDF parser", "CDTR section extraction", "Surveillance Atlas ingestion", "disease-specific datasets"],
        feeds: ecdcStatus.feeds,
        mapLayer: ecdcStatus.mapLayer,
        limitations: ecdcStatus.limitations,
      },
      {
        sourceId: "gdelt",
        status: gdeltStatus.status,
        ready: true,
        requiresApiKey: false,
        sourceRole: gdeltStatus.sourceRole,
        isOfficialSource: false,
        isIncidentSource: false,
        isMediaSignalSource: true,
        runAllDefault: false,
        queryWhitelistRequired: true,
        phase1Capabilities: gdeltStatus.phase1Capabilities,
        phase2Planned: ["Events 2.0 candidate events", "GKG themes/entities/locations", "Visual GKG/image evidence review", "BigQuery/raw data integration"],
        templates: gdeltStatus.templates,
        mapLayer: gdeltStatus.mapLayer,
        limitations: gdeltStatus.limitations,
      },
      {
        sourceId: "copernicus-glofas",
        status: glofasStatus.status,
        ready: glofasStatus.ready,
        requiresApiKey: true,
        requiresConfiguration: glofasStatus.requiresConfiguration,
        requiredEnv: "COPERNICUS_EWDS_API_KEY",
        sourceRole: glofasStatus.sourceRole,
        isForecastSource: true,
        isIncidentSource: false,
        runAllDefault: false,
        phase1Capabilities: glofasStatus.phase1Capabilities,
        mapLayer: glofasStatus.mapLayer,
        limitations: glofasStatus.limitations,
      },
      {
        sourceId: "copernicus-gfm",
        status: gfmStatus.status,
        ready: gfmStatus.ready,
        requiresApiKey: true,
        requiresConfiguration: gfmStatus.requiresConfiguration,
        requiredEnv: "COPERNICUS_GFM_ACCESS_TOKEN",
        sourceRole: gfmStatus.sourceRole,
        isObservationSource: true,
        isIncidentSource: true,
        runAllDefault: false,
        phase1Capabilities: gfmStatus.phase1Capabilities,
        mapLayer: gfmStatus.mapLayer,
        limitations: gfmStatus.limitations,
      },
      {
        sourceId: "usgs_earthquake",
        status: "active",
        ready: true,
        requiresApiKey: false,
        capabilities: ["earthquake_geojson", "technical_seismic_signal"],
      },
      {
        sourceId: "gdacs",
        status: "active",
        ready: true,
        requiresApiKey: false,
        capabilities: ["multi_hazard", "near_real_time", "global_awareness", "rss_fallback"],
      },
      {
        sourceId: "nasa-eonet",
        status: "active",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        capabilities: ["natural_events", "geojson", "json_fallback", "global_awareness", "map_layer:nasa_eonet_natural_events"],
        safetyLimit: "Global awareness only; not a local Chilean authority and not an automatic route/evacuation trigger.",
      },
      {
        sourceId: "usgs-volcano-hans",
        status: "active",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        capabilities: ["volcano_alerts", "recent_notices", "geojson_fallback", "map_layer:usgs_volcano_hans_alerts"],
        limitations: [
          "Official USGS source for USGS monitored volcanoes; not a complete worldwide volcano authority.",
          "Aviation color code is separate from terrestrial alert level and is not an automatic evacuation or route-closure trigger.",
        ],
        coverageNote: "USGS monitored volcanoes; global architecture supports additional regional volcano sources.",
      },
      {
        sourceId: "nws",
        status: "active",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        userAgentConfigured: nwsStatus.userAgentConfigured,
        requiredEnv: "NWS_USER_AGENT",
        warning: nwsStatus.warning,
        capabilities: ["active_alerts", "severity_urgency_certainty", "forecast_context", "map_layer:nws_weather_alerts"],
        limitations: [
          "Official weather alert source for the United States and NWS territories only.",
          "Not a complete worldwide weather source and not an automatic route, evacuation or critical-action trigger.",
        ],
        coverageNote: "United States and NWS territories; global architecture supports additional weather sources.",
      },
      {
        sourceId: "noaa-storm-events",
        status: "active_historical",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        officialSource: true,
        sourceRole: "historical_training_dataset",
        isLiveSource: false,
        coverage: "United States and NOAA/NWS territories",
        importMode: "controlled_year_state_eventType",
        runAllDefault: false,
        capabilities: noaaStormStatus.capabilities,
        mapLayer: noaaStormStatus.mapLayer,
        limitations: noaaStormStatus.limitations,
        dataQualityWarnings: [
          "Official historical data with methodological changes over time.",
          "Possible gaps, inconsistencies and coordinate/damage uncertainty.",
          "Use for historical memory, comparison and training; validate current risk with live official sources.",
        ],
      },
      {
        sourceId: "noaa-ncei-tsunami",
        status: "active_historical",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        officialSource: true,
        sourceRole: "historical_tsunami_dataset",
        isLiveSource: false,
        citationRequired: true,
        citation: noaaNceiTsunamiStatus.citation,
        coverage: noaaNceiTsunamiStatus.coverage,
        importMode: noaaNceiTsunamiStatus.importMode,
        runAllDefault: false,
        capabilities: noaaNceiTsunamiStatus.capabilities,
        mapLayer: noaaNceiTsunamiStatus.mapLayer,
        limitations: noaaNceiTsunamiStatus.limitations,
        phase2Planned: noaaNceiTsunamiStatus.phase2Planned,
        dataQualityWarnings: [
          "Historical tsunami records vary in precision and completeness by age, validity and observation source.",
          "Runups are evidence/observations associated with historical events; ARGUS does not create a KnowledgeIncident per runup.",
          "No inundation geometry is invented by ARGUS from point event/runup records.",
        ],
      },
      {
        sourceId: "noaa-coops",
        status: "active_contextual",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        officialSource: true,
        sourceRole: "coastal_ocean_observation_source",
        isIncidentSource: false,
        coverage: "United States and NOAA CO-OPS monitored coastal stations",
        runAllDefault: false,
        phase1Capabilities: noaaCoopsStatus.phase1Capabilities,
        phase2Planned: noaaCoopsStatus.phase2Planned,
        laterOceanSources: noaaCoopsStatus.laterOceanSources,
        capabilities: noaaCoopsStatus.capabilities,
        mapLayer: {
          id: "noaa-coops-coastal-observations",
          name: noaaCoopsStatus.mapLayer,
          layerType: noaaCoopsStatus.layerType,
          isIncidentLayer: false,
          defaultVisible: false,
          noBulkGlobal: true,
          sublayers: ["Water Level Stations", "Tide Prediction Stations", "Coastal Met Stations", "Air Gap / Bridge Clearance"],
        },
        limitations: noaaCoopsStatus.limitations,
        citationRequired: true,
        citation: noaaCoopsStatus.citation,
        caveat: "Coastal observation context only; not a warning center, evacuation order or official inundation model.",
      },
      {
        sourceId: "ioc-slsmf",
        status: iocSlsmfStatus.status,
        ready: iocSlsmfStatus.apiKeyConfigured,
        requiresApiKey: true,
        requiresConfiguration: iocSlsmfStatus.requiresConfiguration,
        requiredEnv: "IOC_SLSMF_API_KEY",
        officialSource: true,
        sourceRole: "global_sea_level_observation_source",
        isIncidentSource: false,
        coverage: "Global sea level monitoring stations / tide gauges",
        runAllDefault: false,
        accessType: "api_json_requires_key",
        licenseStatus: "registered_api_access",
        citation: iocSlsmfStatus.citation,
        phase1Capabilities: iocSlsmfStatus.phase1Capabilities,
        phase2Planned: iocSlsmfStatus.phase2Planned,
        capabilities: iocSlsmfStatus.capabilities,
        mapLayer: iocSlsmfStatus.mapLayer,
        limitations: iocSlsmfStatus.limitations,
        datumCaution:
          "IOC SLSMF sea level values are relative observations unless a station-specific datum is explicitly available. Do not interpret them as absolute official flood levels.",
        caveat: "Sea level observation context only; not a warning center, evacuation order, tsunami confirmation or official inundation model.",
      },
      {
        sourceId: "openfema",
        status: "active_institutional",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        officialSource: true,
        sourceRole: "disaster_declaration_recovery_dataset",
        isLiveSensor: false,
        coverage: openFemaStatus.coverage,
        importMode: openFemaStatus.importMode,
        runAllDefault: false,
        institutionalLearning: "enabled",
        playbookLearning: "enabled",
        capabilities: openFemaStatus.capabilities,
        mapLayer: openFemaStatus.mapLayer,
        limitations: openFemaStatus.limitations,
        institutionalLearningCapabilities: [
          "declared_disasters",
          "designated_areas",
          "assistance_programs",
          "recovery_context",
          "hazard_mitigation_context",
          "operational_precedents",
          "ARGUS Institutional Playbook input",
        ],
        dataQualityWarnings: [
          "OpenFEMA is official FEMA institutional data, not a live sensor or forecast.",
          "Coverage is limited to the United States and FEMA territories.",
          "ARGUS recommendations based on FEMA precedents are not official FEMA instructions or promises of federal assistance.",
        ],
      },
      {
        sourceId: "open-meteo",
        status: "active",
        ready: true,
        requiresApiKey: false,
        requiresConfiguration: false,
        licenseStatus: "nonCommercialFree",
        commercialUse: "requiresReview",
        institutionalUse: "requiresReview",
        freeUse: "nonCommercial",
        role: "weather_context",
        globalCoverage: true,
        alertSource: false,
        officialSource: false,
        capabilities: [
          "forecast_by_coordinate",
          "weather_context",
          "risk_factors",
          "nav_context",
          "aura_context",
          "fenix_context",
          "map_layer:open_meteo_weather_context",
        ],
        limitations: [
          "Context only; not an official weather alert source.",
          "No global bulk ingestion and no incident creation by default.",
          "No automatic evacuations, route closures or critical orders.",
          "Commercial or institutional use requires review.",
        ],
        coverageNote: "Global by coordinate; forecast_days defaults to 3 and is capped at 3 in this phase.",
      },
      {
        sourceId: "usgs-water",
        status: "active_contextual",
        ready: true,
        requiresApiKey: false,
        optionalApiKey: "USGS_WATER_API_KEY",
        apiKeyConfigured: usgsWaterStatus.apiKeyConfigured,
        apiKeyRequired: false,
        higherRateLimitAvailable: true,
        officialSource: true,
        sourceRole: "hydrological_monitoring_source",
        isIncidentSource: false,
        coverage: "United States and USGS monitored locations",
        modernApiPreferred: true,
        legacyFallbackAvailable: true,
        runAllDefault: false,
        phase1Capabilities: usgsWaterStatus.phase1Capabilities,
        phase2Planned: usgsWaterStatus.phase2Planned,
        capabilities: usgsWaterStatus.capabilities,
        mapLayer: usgsWaterStatus.mapLayer,
        layerType: usgsWaterStatus.layerType,
        isIncidentLayer: false,
        defaultVisible: false,
        parameters: ["00060", "00065"],
        limitations: usgsWaterStatus.limitations,
      },
      {
        sourceId: "openaq",
        status: openAqStatus.status,
        ready: openAqStatus.ready,
        requiresApiKey: true,
        requiresConfiguration: openAqStatus.requiresConfiguration,
        requiredEnv: "OPENAQ_API_KEY",
        officialSource: false,
        aggregatorSource: true,
        sourceRole: "air_quality_observation_source",
        isIncidentSource: false,
        providerDependentReliability: true,
        coverage: "Global aggregated public air quality observations, provider-dependent",
        runAllDefault: false,
        accessType: "api_json_requires_key",
        licenseStatus: "provider_dependent",
        attributionRequired: "check_license",
        commercialUse: "check_license_per_provider",
        phase1Capabilities: openAqStatus.phase1Capabilities,
        phase2Planned: openAqStatus.phase2Planned,
        capabilities: openAqStatus.capabilities,
        mapLayer: openAqStatus.mapLayer,
        limitations: openAqStatus.limitations,
        caveat: "OpenAQ is air quality observation context only; not an official health alert, diagnosis, evacuation order or complete worldwide source.",
      },
      {
        sourceId: "reliefweb",
        status: "requiresConfiguration",
        ready: false,
        requiresConfiguration: true,
        requiredEnv: "RELIEFWEB_APP_NAME",
      },
      {
        sourceId: "nasa_firms",
        status: "requiresApiKey",
        ready: false,
        requiresApiKey: true,
        requiredEnv: "NASA_FIRMS_MAP_KEY",
      },
    ],
    sources: stats,
    incidentCount: demoKnowledgeIncidents.length,
    lessonCount: demoKnowledgeLessons.length,
    persistentMemory: dbHealth,
    lastIngestionRuns: [
      {
        id: "hdx-hapi-context-ready",
        sourceId: "hdx-hapi",
        status: hapiStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/hdx-hapi or /api/knowledge-intake/jobs/run-hdx-hapi-context. Not run-all default.",
      },
      {
        id: "who-don-ready",
        sourceId: "who-don",
        status: whoDonStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/who-don or /api/knowledge-intake/jobs/run-who-don.",
      },
      {
        id: "ecdc-ready",
        sourceId: "ecdc",
        status: "active_contextual_incident_capable",
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/ecdc or /api/knowledge-intake/jobs/run-ecdc. CDTR evidence by default.",
      },
      {
        id: "gdelt-context-ready",
        sourceId: "gdelt",
        status: gdeltStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/gdelt or /api/knowledge-intake/jobs/run-gdelt-context. Not run-all default.",
      },
      {
        id: "copernicus-glofas-ready",
        sourceId: "copernicus-glofas",
        status: glofasStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/copernicus-glofas or /api/knowledge-intake/jobs/run-copernicus-glofas-context. Not run-all default.",
      },
      {
        id: "copernicus-gfm-ready",
        sourceId: "copernicus-gfm",
        status: gfmStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/copernicus-gfm or /api/knowledge-intake/jobs/run-copernicus-gfm-context. Not run-all default.",
      },
      {
        id: "usgs-live-ready",
        sourceId: "usgs_earthquake",
        status: "ready",
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/usgs.",
      },
      {
        id: "gdacs-live-ready",
        sourceId: "gdacs",
        status: "ready",
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/gdacs or /api/knowledge-intake/jobs/run-gdacs.",
      },
      {
        id: "eonet-live-ready",
        sourceId: "nasa-eonet",
        status: "ready",
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/eonet or /api/knowledge-intake/jobs/run-eonet.",
      },
      {
        id: "usgs-volcano-hans-live-ready",
        sourceId: "usgs-volcano-hans",
        status: "ready",
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/usgs-volcano-hans or /api/knowledge-intake/jobs/run-usgs-volcano-hans.",
      },
      {
        id: "nws-live-ready",
        sourceId: "nws",
        status: nwsStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/nws or /api/knowledge-intake/jobs/run-nws.",
      },
      {
        id: "open-meteo-context-ready",
        sourceId: "open-meteo",
        status: openMeteoStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/open-meteo or as contextual enrichment through /api/knowledge-intake/jobs/run-open-meteo-context.",
      },
      {
        id: "osm-overpass-context-ready",
        sourceId: "osm-overpass",
        status: osmStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/osm-overpass or as controlled critical infrastructure enrichment through /api/knowledge-intake/jobs/run-osm-overpass-context. Not run-all default.",
      },
      {
        id: "usgs-water-context-ready",
        sourceId: "usgs-water",
        status: usgsWaterStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/usgs-water or as hydrological enrichment through /api/knowledge-intake/jobs/run-usgs-water-context. Not run-all default.",
      },
      {
        id: "noaa-coops-context-ready",
        sourceId: "noaa-coops",
        status: noaaCoopsStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/noaa-coops or as controlled coastal enrichment through /api/knowledge-intake/jobs/run-noaa-coops-context. Not run-all default.",
      },
      {
        id: "ioc-slsmf-context-ready",
        sourceId: "ioc-slsmf",
        status: iocSlsmfStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/ioc-slsmf or as controlled sea level context through /api/knowledge-intake/jobs/run-ioc-slsmf-context. Not run-all default.",
      },
      {
        id: "openaq-context-ready",
        sourceId: "openaq",
        status: openAqStatus.status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/openaq or as controlled air quality context through /api/knowledge-intake/jobs/run-openaq-context. Not run-all default.",
      },
      {
        id: "noaa-storm-events-historical-ready",
        sourceId: "noaa-storm-events",
        status: noaaStormStatus.status,
        normalizedCount: 0,
        note: "Controlled historical preview/import only through /api/knowledge-intake/live/noaa-storm-events or /api/knowledge-intake/jobs/import-noaa-storm-events. Not run-all default.",
      },
      {
        id: "noaa-ncei-tsunami-historical-ready",
        sourceId: "noaa-ncei-tsunami",
        status: noaaNceiTsunamiStatus.status,
        normalizedCount: 0,
        note: "Controlled historical preview/import only through /api/knowledge-intake/live/noaa-ncei-tsunami or /api/knowledge-intake/jobs/import-noaa-ncei-tsunami. Not run-all default.",
      },
      {
        id: "openfema-institutional-ready",
        sourceId: "openfema",
        status: openFemaStatus.status,
        normalizedCount: 0,
        note: "Controlled institutional preview/import only through /api/knowledge-intake/live/openfema or /api/knowledge-intake/jobs/import-openfema-disaster-declarations. Not run-all default.",
      },
      {
        id: "reliefweb-live-ready",
        sourceId: "reliefweb",
        status: reliefwebAdapter().status,
        normalizedCount: 0,
        note: "Runs on demand through /api/knowledge-intake/live/reliefweb.",
      },
      {
        id: "firms-key-check",
        sourceId: "nasa_firms",
        status: firmsAdapter().status,
        normalizedCount: 0,
        note: firmsAdapter().message,
      },
    ],
    adapterStatus: [usgsAdapter(), earthquakeImpactStatus, getGdacsAdapterStatus(), getEonetAdapterStatus(), getUsgsVolcanoHansAdapterStatus(), gvpStatus, nwsStatus, noaaStormStatus, noaaNceiTsunamiStatus, noaaCoopsStatus, iocSlsmfStatus, openFemaStatus, openMeteoStatus, usgsWaterStatus, openAqStatus, osmStatus, hapiStatus, whoDonStatus, ecdcStatus, gdeltStatus, glofasStatus, gfmStatus, reliefwebAdapter(), firmsAdapter()],
    licenseWarnings: [
      {
        sourceId: "open-meteo",
        licenseStatus: "nonCommercialFree",
        commercialUse: "requiresReview",
        institutionalUse: "requiresReview",
        note: "Review Open-Meteo paid API or self-hosting before contractual commercial/institutional use.",
      },
      {
        sourceId: "openaq",
        licenseStatus: "provider_dependent",
        commercialUse: "check_license_per_provider",
        attributionRequired: "check_license",
        note: "Preserve OpenAQ plus provider/owner/license metadata; do not assume commercial reuse is allowed universally.",
      },
    ],
    parserStatus: parserInputs.map((inputType) => ({
      inputType,
      processor: planKnowledgeIngestion(inputType),
      status: inputType === "pdf" || inputType === "docx" || inputType === "xlsx" ? "parser_stub_or_text_preview" : "available",
    })),
    warnings: [
      "USGS, GDACS, NASA EONET and ReliefWeb execute only when their live endpoints are called.",
      "USGS ShakeMap/PAGER enrich USGS earthquake events with estimated shaking and impact; they do not confirm damage, casualties, evacuations or route closures.",
      "GDACS is a global awareness source and must not be presented as a local Chilean authority.",
      "NASA EONET is a NASA global natural-events source and must not be presented as a local Chilean authority or automatic critical-action trigger.",
      "USGS Volcano HANS is official for USGS monitored volcanoes, not a complete worldwide local volcano authority.",
      "Smithsonian GVP is global volcanism memory and report context; catalog/history do not create incidents and GVP never replaces local volcano observatories.",
      ...(nwsStatus.userAgentConfigured ? [] : ["NWS_USER_AGENT missing. NWS uses ARGUS/preview (contact-not-configured) fallback in preview/dev."]),
      "NWS is official for the United States and NWS territories only; ARGUS remains extensible for Open-Meteo, MET Norway, WMO and national weather agencies.",
      "NOAA Storm Events is a historical NOAA/NCEI dataset only; it is not live, not forecast, not global weather coverage and not run-all default.",
      "NOAA NCEI Historical Tsunami is global historical memory only; it is not a live warning center, evacuation order, local authority or official inundation model.",
      "NOAA CO-OPS is official coastal observation context for United States and NOAA monitored stations only; it is not a global warning center, evacuation order, official inundation model or run-all default job.",
      "IOC SLSMF requires IOC_SLSMF_API_KEY and is global relative sea level observation context only; it is not a warning center, evacuation order, tsunami confirmation, absolute datum source or run-all default job.",
      "OpenFEMA is an institutional FEMA dataset only; it is not live, not forecast, not worldwide coverage and not run-all default.",
      "Open-Meteo is active as global weather context only; it is not an official alert source and commercial/institutional use requires review.",
      "OpenAQ requires OPENAQ_API_KEY and is contextual air quality observation only; it is not an official health alert, medical diagnosis, evacuation order, complete worldwide source or incident source.",
      "USGS Water Data is active as official US hydrological context only; it is not worldwide coverage, a forecast, evacuation order, route closure or run-all default job.",
      "OpenStreetMap / Overpass is active as collaborative critical infrastructure context only; it is not an official universal registry, routing engine, geocoder, public tile backend, availability source or run-all default job.",
      "ReliefWeb v2 requires an approved RELIEFWEB_APP_NAME.",
      "HDX/OCHA HAPI requires HAPI_APP_IDENTIFIER and is humanitarian context only; no indicator creates a KnowledgeIncident.",
      "WHO DON is official public health reporting, not diagnosis, local surveillance completeness, automatic restrictions or citizen alerts.",
      "ECDC RSS/data is EU/EEA public health context; CDTR reports are evidence by default and EpiPulse/EWRS are not integrated.",
      "GDELT is OSINT/media signal only; it is not an official confirmation source and never creates confirmed incidents by itself.",
      "Copernicus GloFAS requires EWDS credentials and is forecast/model context only; GFM requires access token and satellite observation caveats apply.",
      "NASA FIRMS requires NASA_FIRMS_MAP_KEY and remains disabled without it.",
      "Manual/file imports are preview normalization until storage and admin review are connected.",
    ],
    criticalMissingCapabilities: [
      "No storage, OCR, RAG or pgvector persistence is enabled yet.",
      "No automatic insertion into the operational map is enabled; map-events endpoint is read-only.",
      "No production ingestion scheduler exists.",
    ],
    limitations: [
      "Human validation is required before operational decisions.",
      "Volcano alert level and aviation color code must remain separate operational signals.",
      "ARGUS is prepared to add SERNAGEOMIN, JMA, IMO, PHIVOLCS, GNS Science, INGV, VAAC, DYFI, ShakeMap grid/raster analytics and local earthquake authorities later without replacing local authorities.",
      "Smithsonian GVP catalog/history support volcanic memory, Risk, Fenix, NAV, AURA and map context, but never automatic incidents, evacuation orders, route closures, ashfall modelling or diagnosis.",
      "USGS ShakeMap/PAGER support impact prioritization by MMI/exposure/PAGER, but never confirmed deaths, injuries, damage or official local orders.",
      "Open-Meteo context may support Risk, Fenix, NAV and AURA analysis, but requires official validation for critical decisions.",
      "OpenAQ context may support smoke, wildfire, volcano, dust, urban pollution, Risk, Fenix, NAV, AURA, Command Center and map context, but never automatic health alerts, diagnoses, evacuations or smoke-fire causal attribution.",
      "USGS Water context may support Risk, Fenix, NAV, AURA and Command Center hydrological panels, but sensor readings alone are not official flood orders.",
      "NOAA CO-OPS context may support tsunami, hurricane, storm surge, NAV, Fenix, AURA, Command Center and map context, but never automatic warnings, bridge closures, evacuation orders or invented inundation zones.",
      "IOC SLSMF context may support tsunami, coastal, storm surge, NAV, Fenix, AURA, Command Center and map context, but never automatic tsunami confirmation, evacuation orders or invented flood levels.",
      "NOAA Storm Events may support historical memory, Risk, Fenix, NAV, AURA and map context, but never automatic critical decisions.",
      "NOAA NCEI Historical Tsunami may support tsunami memory, Risk, Fenix, NAV, AURA, Command Center and map context, but never automatic live warnings or invented inundation zones.",
      "OpenFEMA may support institutional memory, Risk, Fenix, NAV, AURA and map context, but never official FEMA instructions or automatic critical decisions.",
      "OpenStreetMap / Overpass may support AURA, Fenix, NAV, Risk, Command Center and map context, but every recommendation must preserve OSM attribution and collaborative-data caveats.",
    ],
    dataQualityWarnings: [
      {
        sourceId: "noaa-storm-events",
        warnings: [
          "Official NOAA/NCEI historical records, not live alerts.",
          "Methodology, event types, completeness, damage values and coordinate precision vary over historical periods.",
        ],
      },
      {
        sourceId: "noaa-ncei-tsunami",
        warnings: [
          "Official NOAA/NCEI/WDS historical tsunami records, not live alerts.",
          "Event source and runup observations can be approximate, especially for older events.",
          "Citation required: NCEI/WDS Global Historical Tsunami Database, DOI 10.7289/V5PN93H7.",
        ],
      },
      {
        sourceId: "openfema",
        warnings: [
          "Official FEMA/OpenFEMA Disaster Declarations Summaries, not live alerts.",
          "Declarations and assistance programs are institutional records; do not infer current eligibility, route closures, evacuations or federal assistance promises.",
        ],
      },
    ],
  });
}
