export const usgsEarthquakeImpactMapLayers = [
  {
    id: "usgs-shakemap-intensity",
    name: "USGS ShakeMap Intensity",
    sourceId: "usgs-shakemap",
    layerType: "earthquake_shaking_intensity",
    isIncidentLayer: false,
    isEnrichmentLayer: true,
    defaultVisible: true,
    requiresConfiguration: false,
    attributionRequired: true,
    sublayers: ["MMI Intensity", "PGA", "PGV", "PSA 0.3s", "PSA 1.0s", "PSA 3.0s", "ShakeMap Contours", "ShakeMap Grid", "Fault Geometry", "Stations", "Uncertainty"],
    caveats: ["ShakeMap is estimated/modelled shaking context; it does not confirm damage or order evacuations."],
  },
  {
    id: "usgs-pager-impact-assessment",
    name: "USGS PAGER Impact Assessment",
    sourceId: "usgs-pager",
    layerType: "earthquake_impact_assessment",
    isIncidentLayer: false,
    isEnrichmentLayer: true,
    defaultVisible: true,
    requiresConfiguration: false,
    attributionRequired: true,
    estimatedImpactCaveat: true,
    sublayers: ["Population Exposure by MMI", "Fatality Alert", "Economic Loss Alert", "Affected Cities", "Impact Summary", "Secondary Hazard Notes"],
    caveats: ["PAGER impact values are estimates, not confirmed deaths, injuries, damage or losses."],
  },
] as const;
