import type { TalosAssessmentInput, TalosRiskAssessment } from "@/modules/talos/types";
import { calculateTalosRiskAssessment } from "@/modules/talos/talosScoring";

/**
 * Escenarios demo profesionales, ejecutados a través del motor real
 * (`calculateTalosRiskAssessment`) para garantizar consistencia interna —
 * no son objetos armados a mano que podrían desalinearse del scoring real.
 * Sin personas reales, sin datos sensibles. Marcados `isDemo: true`.
 */
const demoInputs: TalosAssessmentInput[] = [
  {
    event: {
      id: "talos-demo-wildfire",
      title: "Incendio forestal en zona periurbana",
      category: "fire",
      severity: "CRITICAL",
      status: "UNDER_REVIEW",
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      location: { lat: -33.38, lng: -70.72, label: "Ladera periurbana, sector poniente" },
    },
    vigiaSignal: {
      reportCount: 4,
      confirmedCount: 1,
      criticalCount: 2,
      recentCount: 3,
      averageReputation: 55,
      reportsWithEvidence: 2,
      possibleDuplicates: 1,
      location: { lat: -33.38, lng: -70.72 },
      category: "fire",
    },
    oraculoSignal: {
      verifiedCount: 0,
      averageConfidenceScore: 58,
      officialSourceCount: 0,
      citizenSourceCount: 2,
      contradictionCount: 0,
      oldestEvidenceHours: 0.5,
      hasLicensePendingSource: false,
    },
    context: { populationExposureEstimate: 4200, nearCriticalInfrastructure: true, routesAffected: true, weatherRisk: "high", medicalImpact: "low" },
  },
  {
    event: {
      id: "talos-demo-flood",
      title: "Inundación urbana en paso bajo nivel",
      category: "flood",
      severity: "HIGH",
      status: "UNDER_REVIEW",
      createdAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      location: { lat: -33.51, lng: -70.71, label: "Paso bajo nivel, sector poniente" },
    },
    vigiaSignal: {
      reportCount: 2,
      confirmedCount: 0,
      criticalCount: 0,
      recentCount: 1,
      averageReputation: 35,
      reportsWithEvidence: 0,
      possibleDuplicates: 0,
      category: "flood",
    },
    oraculoSignal: {
      verifiedCount: 0,
      averageConfidenceScore: 40,
      officialSourceCount: 0,
      citizenSourceCount: 2,
      contradictionCount: 0,
      oldestEvidenceHours: 1.2,
      hasLicensePendingSource: false,
    },
    context: { routesAffected: true, weatherRisk: "medium", logisticsImpact: "low" },
  },
  {
    event: {
      id: "talos-demo-earthquake",
      title: "Sismo moderado percibido",
      category: "earthquake",
      severity: "MEDIUM",
      status: "VALIDATED",
      createdAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 148 * 60 * 1000).toISOString(),
      location: { lat: -33.45, lng: -70.65, label: "Región metropolitana" },
    },
    oraculoSignal: {
      verifiedCount: 1,
      averageConfidenceScore: 92,
      officialSourceCount: 1,
      citizenSourceCount: 0,
      contradictionCount: 0,
      oldestEvidenceHours: 2.5,
      hasLicensePendingSource: false,
    },
    context: { nearCriticalInfrastructure: false },
  },
  {
    event: {
      id: "talos-demo-road-block",
      title: "Corte de ruta con impacto logístico",
      category: "infrastructure",
      severity: "MEDIUM",
      status: "VALIDATED",
      createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      location: { lat: -33.47, lng: -70.64, label: "Avenida principal, sector oriente" },
    },
    vigiaSignal: {
      reportCount: 1,
      confirmedCount: 1,
      criticalCount: 0,
      recentCount: 0,
      averageReputation: 78,
      reportsWithEvidence: 1,
      possibleDuplicates: 0,
      category: "road_block",
    },
    context: { routesAffected: true, logisticsImpact: "medium" },
  },
  {
    event: {
      id: "talos-demo-mass-medical",
      title: "Emergencia médica masiva (evento simulado)",
      category: "medical",
      severity: "CRITICAL",
      status: "ESCALATED",
      createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      location: { lat: -33.45, lng: -70.66, label: "Zona centro, vía pública", isApproximate: true },
    },
    vigiaSignal: {
      reportCount: 3,
      confirmedCount: 1,
      criticalCount: 3,
      recentCount: 3,
      averageReputation: 60,
      reportsWithEvidence: 0,
      possibleDuplicates: 0,
      category: "medical_emergency",
    },
    context: { medicalImpact: "critical", populationExposureEstimate: 300 },
  },
  {
    event: {
      id: "talos-demo-infrastructure-damage",
      title: "Poste eléctrico dañado",
      category: "infrastructure",
      severity: "HIGH",
      status: "ESCALATED",
      createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      location: { lat: -33.42, lng: -70.58, label: "Sector residencial, calle secundaria" },
    },
    vigiaSignal: {
      reportCount: 1,
      confirmedCount: 1,
      criticalCount: 0,
      recentCount: 0,
      averageReputation: 81,
      reportsWithEvidence: 1,
      possibleDuplicates: 0,
      category: "power_outage",
    },
    context: { nearCriticalInfrastructure: true },
  },
  {
    event: {
      id: "talos-demo-contradictory",
      title: "Reporte contradictorio de accidente vial",
      category: "traffic",
      severity: "MEDIUM",
      status: "UNDER_REVIEW",
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
      location: { lat: -33.44, lng: -70.61, label: "Cruce vial, sector centro" },
    },
    vigiaSignal: {
      reportCount: 1,
      confirmedCount: 0,
      criticalCount: 0,
      recentCount: 1,
      averageReputation: 55,
      reportsWithEvidence: 0,
      possibleDuplicates: 0,
      category: "traffic_accident",
    },
    oraculoSignal: {
      verifiedCount: 1,
      averageConfidenceScore: 65,
      officialSourceCount: 1,
      citizenSourceCount: 1,
      contradictionCount: 1,
      oldestEvidenceHours: 0.3,
      hasLicensePendingSource: false,
    },
  },
  {
    event: {
      id: "talos-demo-insufficient-evidence",
      title: "Evento crítico con evidencia insuficiente",
      category: "public_security",
      severity: "CRITICAL",
      status: "NEW",
      createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      location: { label: "Zona no confirmada", isApproximate: true },
    },
  },
];

export const talosDemoAssessments: TalosRiskAssessment[] = demoInputs.map((input) => ({
  ...calculateTalosRiskAssessment(input),
  isDemo: true,
}));
