import type { MapLayerMode, MapLayerPolicy } from "@/lib/source-governance/mapLayerTaxonomy";
import type { SourceContextState } from "@/lib/source-governance/sourceRoles";

function layer(input: MapLayerPolicy): MapLayerPolicy {
  return input;
}

const ALL_COMMAND_MODES: MapLayerMode[] = ["command_center", "analyst", "risk"];
const ALL_CONTEXT_MODES: MapLayerMode[] = ["command_center", "analyst", "fenix", "nav", "aura", "risk"];

export const MAP_LAYER_REGISTRY: MapLayerPolicy[] = [
  layer({ layerId: "user-location", sourceId: "user", group: "core", label: "User location", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "nav"], caveats: [], legendType: "point", priority: 1 }),
  layer({ layerId: "sos", sourceId: "user-report", group: "core", label: "SOS", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "aura"], caveats: ["User reports remain independent and require validation/reputation handling."], legendType: "point", priority: 2 }),
  layer({ layerId: "active-official-incidents", sourceId: "multi-official", group: "live_incidents", label: "Active official incidents", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "fenix", "nav", "aura", "risk"], caveats: ["Only confirmed/live incidents are citizen default."], legendType: "hybrid", priority: 3, badges: ["OFFICIAL"] }),
  layer({ layerId: "nearby-incidents", sourceId: "multi-official", group: "live_incidents", label: "Nearby incidents", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "nav"], caveats: [], legendType: "point", priority: 4 }),
  layer({ layerId: "usgs-earthquake-relevant", sourceId: "usgs-earthquake", group: "earthquake", label: "USGS earthquakes", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "fenix", "risk"], caveats: ["Magnitude/depth are source-reported and may update."], legendType: "point", priority: 5, badges: ["OFFICIAL"] }),
  layer({ layerId: "noaa-tsunami-active", sourceId: "noaa-tsunami", group: "tsunami_coastal", label: "NOAA tsunami active", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "nav", "risk"], caveats: ["Follow official local authority instructions."], legendType: "polygon", priority: 6, badges: ["OFFICIAL"] }),
  layer({ layerId: "nhc-cphc-active-storms", sourceId: "noaa-nhc-cphc", group: "weather_cyclone", label: "NHC/CPHC active storms", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "fenix", "nav", "risk"], caveats: ["Forecast cones/tracks are model/forecast context."], legendType: "hybrid", priority: 7, badges: ["OFFICIAL", "FORECAST"] }),
  layer({ layerId: "nws-gdacs-alerts", sourceId: "multi-official-alerts", group: "official_alerts", label: "NWS/GDACS alerts", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "risk"], caveats: [], legendType: "hybrid", priority: 8, badges: ["OFFICIAL"] }),
  layer({ layerId: "nasa-firms-relevant", sourceId: "nasa-firms", group: "observed_reality", label: "FIRMS relevant fire detections", defaultVisibleCitizen: true, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["citizen", "command_center", "analyst", "fenix", "aura", "risk"], requiresActiveIncident: true, caveats: ["Thermal detections are not evacuation orders or damage confirmation."], legendType: "point", priority: 9, badges: ["OBSERVED"] }),
  layer({ layerId: "observed-flood-relevant", sourceId: "copernicus-gfm", group: "flood", label: "Observed flood", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["command_center", "analyst", "fenix", "nav", "risk"], requiresAoi: true, caveats: ["Satellite observed flood requires AOI/product context and review."], legendType: "raster", priority: 20, badges: ["OBSERVED", "REQUIRES REVIEW", "CONFIG REQUIRED"] }),

  layer({ layerId: "usgs-shakemap", sourceId: "usgs-shakemap", group: "impact_enrichment", label: "ShakeMap", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_CONTEXT_MODES, requiresSelectedIncident: true, caveats: ["Intensity context; not damage confirmation."], legendType: "raster", priority: 30, badges: ["OBSERVED", "ESTIMATED IMPACT"] }),
  layer({ layerId: "usgs-pager", sourceId: "usgs-pager", group: "impact_enrichment", label: "PAGER", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_CONTEXT_MODES, requiresSelectedIncident: true, caveats: ["Estimated impact; casualties/damage are not confirmed."], legendType: "panel", priority: 31, badges: ["ESTIMATED IMPACT"] }),
  layer({ layerId: "open-meteo-context", sourceId: "open-meteo", group: "forecast_models", label: "Open-Meteo", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_CONTEXT_MODES, requiresAoi: true, caveats: ["Forecast/model, not observed reality."], legendType: "timeline", priority: 32, badges: ["FORECAST"] }),
  layer({ layerId: "glofas", sourceId: "copernicus-glofas", group: "forecast_models", label: "GloFAS", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["command_center", "analyst", "fenix", "risk"], requiresAoi: true, caveats: ["Flood forecast/model only; no confirmed incident by itself."], legendType: "raster", priority: 33, badges: ["FORECAST", "CONFIG REQUIRED"] }),
  layer({ layerId: "openaq-context", sourceId: "openaq", group: "aura", label: "OpenAQ", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["command_center", "analyst", "aura", "fenix", "risk"], requiresAoi: true, caveats: ["Provider-dependent air observations; not a medical diagnosis or local official health order."], legendType: "point", priority: 34, badges: ["OBSERVED", "CONTEXT"] }),
  layer({ layerId: "osm-infrastructure", sourceId: "osm-overpass", group: "infrastructure_context", label: "OSM nearby infrastructure", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_CONTEXT_MODES, requiresAoi: true, caveats: ["Community map data; not official availability or route closure information."], legendType: "point", priority: 35, badges: ["CONTEXT"] }),
  layer({ layerId: "hdx-hapi-context", sourceId: "hdx-hapi", group: "infrastructure_context", label: "HDX/HAPI", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["command_center", "analyst", "fenix", "aura", "risk"], requiresAoi: true, caveats: ["Humanitarian context is reference-period dependent."], legendType: "panel", priority: 36, badges: ["CONTEXT", "CONFIG REQUIRED"] }),
  layer({ layerId: "coastal-ocean-context", sourceId: "noaa-coops", group: "tsunami_coastal", label: "CO-OPS/NDBC/IOC", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_CONTEXT_MODES, requiresAoi: true, caveats: ["Observation context only; not a tsunami warning center."], legendType: "point", priority: 37, badges: ["OBSERVED"] }),
  layer({ layerId: "usgs-water-context", sourceId: "usgs-water", group: "flood", label: "USGS Water", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_CONTEXT_MODES, requiresAoi: true, caveats: ["Hydrological monitoring context; not an evacuation order."], legendType: "point", priority: 38, badges: ["OBSERVED"] }),

  layer({ layerId: "candidate-incidents", sourceId: "candidate", group: "command_center", label: "Candidate incidents", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_COMMAND_MODES, caveats: ["Requires validation before citizen exposure."], legendType: "point", priority: 50, badges: ["REQUIRES REVIEW"] }),
  layer({ layerId: "source-health", sourceId: "source-health", group: "health", label: "Source Health", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_COMMAND_MODES, caveats: ["Operational diagnostics only."], legendType: "panel", priority: 51 }),
  layer({ layerId: "raw-evidence", sourceId: "raw-evidence", group: "command_center", label: "Raw Evidence", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ALL_COMMAND_MODES, caveats: ["Label source and caveats before use."], legendType: "panel", priority: 52 }),
  layer({ layerId: "historical-datasets", sourceId: "historical", group: "historical_memory", label: "Historical datasets", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["command_center", "analyst", "fenix", "risk"], caveats: ["Historical memory, not live incident state."], legendType: "timeline", priority: 53, badges: ["HISTORICAL"] }),
  layer({ layerId: "gdelt-media-signals", sourceId: "gdelt", group: "osint_signals", label: "GDELT media signals", defaultVisibleCitizen: false, defaultVisibleCommandCenter: true, defaultVisibleAnalyst: true, visibleInModes: ["command_center", "analyst"], requiresSelectedIncident: true, caveats: ["OSINT media signal; never confirms incidents by itself."], legendType: "timeline", priority: 60, badges: ["OSINT", "REQUIRES REVIEW"] }),
];

export function getAllMapLayerPolicies() {
  return MAP_LAYER_REGISTRY;
}

export function filterMapLayersByMode(mode: MapLayerMode, context: SourceContextState = {}) {
  return MAP_LAYER_REGISTRY
    .filter((layer) => layer.visibleInModes.includes(mode))
    .filter((layer) => !layer.requiresActiveIncident || context.hasActiveIncident)
    .filter((layer) => !layer.requiresSelectedIncident || context.hasSelectedIncident)
    .filter((layer) => !layer.requiresAoi || context.hasAoi || context.hasBbox || context.hasPoint)
    .sort((a, b) => a.priority - b.priority);
}
