import type { OraculoEvidence } from "@/modules/oraculo/types";

/**
 * Evidencia demo profesional, usada solo cuando no hay suficiente evidencia
 * real recolectada (entorno local/demo). Sin personas reales, sin datos
 * sensibles. Etiquetada explícitamente con `isDemo: true`.
 */
export const oraculoDemoEvidence: OraculoEvidence[] = [
  {
    id: "oraculo-demo-quake",
    title: "Sismo moderado detectado",
    summary: "Evento sísmico de magnitud moderada detectado por red geológica oficial.",
    sourceId: "usgs_earthquake",
    sourceName: "USGS Earthquake Hazards",
    sourceType: "government",
    category: "earthquake",
    relatedEventId: "atlas-demo-earthquake",
    observedAt: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 148 * 60 * 1000).toISOString(),
    location: { lat: -33.45, lng: -70.65, label: "Región metropolitana" },
    confidence: "verified",
    reliabilityScore: 92,
    verificationStatus: "verified",
    contradictionStatus: "none",
    tags: ["earthquake", "official"],
    attribution: "USGS",
    isDemo: true,
  },
  {
    id: "oraculo-demo-wildfire-vigia",
    title: "Incendio forestal reportado por VIGÍA",
    summary: "Reporte ciudadano de foco de incendio, respaldado por contexto meteorológico de viento fuerte en la zona.",
    sourceId: "argus-vigia-reports",
    sourceName: "ARGUS VIGÍA",
    sourceType: "citizen",
    category: "wildfire",
    relatedReportId: "vigia-demo-wildfire",
    relatedModule: "VIGIA",
    observedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    location: { lat: -33.38, lng: -70.72, label: "Ladera periurbana, sector poniente" },
    confidence: "medium",
    reliabilityScore: 58,
    verificationStatus: "pending_review",
    contradictionStatus: "none",
    tags: ["fire", "citizen_report"],
    attribution: "Vecino-4420",
    isDemo: true,
  },
  {
    id: "oraculo-demo-weather-support",
    title: "Contexto meteorológico de viento fuerte",
    summary: "Pronóstico de vientos sostenidos sobre 40 km/h en la misma zona del foco reportado.",
    sourceId: "open-meteo",
    sourceName: "Open-Meteo",
    sourceType: "government",
    category: "weather",
    relatedReportId: "vigia-demo-wildfire",
    observedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    location: { lat: -33.38, lng: -70.72, label: "Ladera periurbana, sector poniente" },
    confidence: "high",
    reliabilityScore: 78,
    verificationStatus: "verified",
    contradictionStatus: "none",
    tags: ["weather", "context_only"],
    attribution: "Open-Meteo",
    isDemo: true,
  },
  {
    id: "oraculo-demo-weather-alert",
    title: "Alerta meteorológica institucional",
    summary: "Aviso de vientos fuertes emitido por servicio meteorológico oficial para la zona centro-sur.",
    sourceId: "nws",
    sourceName: "NWS / api.weather.gov",
    sourceType: "government",
    category: "weather",
    observedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 118 * 60 * 1000).toISOString(),
    location: { lat: -36.82, lng: -73.05, label: "Zona costera centro-sur" },
    confidence: "verified",
    reliabilityScore: 88,
    verificationStatus: "verified",
    contradictionStatus: "none",
    tags: ["weather", "official"],
    attribution: "NWS",
    isDemo: true,
  },
  {
    id: "oraculo-demo-conflict-osint",
    title: "Señal OSINT de crisis internacional",
    summary: "Cobertura mediática global detecta aumento de menciones sobre disturbios civiles en la región monitoreada.",
    sourceId: "gdelt",
    sourceName: "GDELT",
    sourceType: "media",
    category: "conflict",
    observedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 190 * 60 * 1000).toISOString(),
    location: { label: "Contexto regional", isApproximate: true },
    confidence: "low",
    reliabilityScore: 42,
    verificationStatus: "unverified",
    contradictionStatus: "none",
    tags: ["conflict", "osint", "media_signal"],
    attribution: "GDELT Project",
    notes: "Señal de contexto mediático; no confirma incidente por sí sola.",
    isDemo: true,
  },
  {
    id: "oraculo-demo-pending-no-evidence",
    title: "Reporte ciudadano pendiente sin evidencia",
    summary: "Reporte de anegamiento sin fotografías ni confirmación adicional.",
    sourceId: "argus-vigia-reports",
    sourceName: "ARGUS VIGÍA",
    sourceType: "citizen",
    category: "flood",
    relatedReportId: "vigia-demo-flood",
    relatedModule: "VIGIA",
    observedAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    location: { lat: -33.51, lng: -70.71, label: "Paso bajo nivel, sector poniente" },
    confidence: "low",
    reliabilityScore: 25,
    verificationStatus: "unverified",
    contradictionStatus: "none",
    tags: ["flood", "no_evidence"],
    isDemo: true,
  },
  {
    id: "oraculo-demo-contradiction-citizen",
    title: "Reporte ciudadano de accidente vial",
    summary: "Reporte ciudadano indica accidente con víctimas; fuente institucional aún no lo confirma.",
    sourceId: "argus-vigia-reports",
    sourceName: "ARGUS VIGÍA",
    sourceType: "citizen",
    category: "infrastructure",
    observedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    location: { lat: -33.44, lng: -70.61, label: "Cruce vial, sector centro" },
    confidence: "medium",
    reliabilityScore: 48,
    verificationStatus: "pending_review",
    contradictionStatus: "possible",
    tags: ["traffic_accident"],
    attribution: "Vecino-3307",
    isDemo: true,
  },
  {
    id: "oraculo-demo-official-no-accident",
    title: "Fuente institucional descarta incidente vial",
    summary: "Reporte institucional indica que no hay registro de accidente en la ubicación señalada.",
    sourceId: "argus-core-events",
    sourceName: "ARGUS Core Events",
    sourceType: "internal",
    category: "infrastructure",
    observedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    location: { lat: -33.44, lng: -70.61, label: "Cruce vial, sector centro" },
    confidence: "high",
    reliabilityScore: 70,
    verificationStatus: "verified",
    contradictionStatus: "possible",
    tags: ["traffic_accident", "institutional"],
    isDemo: true,
  },
];
